### ISSUE TITLE
Jellyfish Controller continually going 'unavailable'

### ISSUE THREAD

**Issue by markus99** [bdunn44/hass-jellyfish-lighting#20]
I've hardwired the controller into my network, yet HA (~20+ times a day) shows as 'unavailable'

![image](https://github.com/bdunn44/hass-jellyfish-lighting/assets/2835274/c9b92c7e-51ec-492a-8fe6-26671d7821e8)

Possible to update so only if it's unavailable for >60 seconds it registers?

**Comment by bdunn44** [comment]
Hi there, thank you for reporting this issue. I checked my logs and have the same issue intermittently. And you're right, it's a timeout issue. Right now the integration polls the Jellyfish controller every 15 seconds for new data, and this request will time out if there's no response after 10 seconds. It seems the controller sometimes gets bogged down and doesn't respond in time - and 10 seconds is honestly an eternity!

Your proposed solution is definitely an option but would result in pretty high lag (i.e. there would be a >15s delay for any state changes to be reflected in HA if you were controlling lights via the Jellyfish app, for example). I'm thinking the best fix for this would be to move away from polling altogether and leverage the push updates that are sent via the controller. If the push updates work well - I don't see any reason why they wouldn't - it's also much more efficient for HA & your network, and state updates will reflect in HA instantaneously. A nice upgrade all around. 

This has been on my mind for a while but I never got around to it because polling "just worked". Let me look into it, and fingers crossed, I'll release an update soon with push enabled.

**Comment by bdunn44** [comment]
Quick update, I modified the integration to enable push (781644e20874b8a898c04774ba5eac93df413aa0) and it seems to be working pretty well. The underlying library needs a slight upgrade though - I've submitted a PR that will need to be merged before this is released:

https://github.com/vinenoobjelly/jellyfishlights-py/pull/10

**Comment by bdunn44** [comment]
@markus99 I just released version 1.3.0 which should address this. It's a beta release at the moment. Please give it a shot and reopen this issue and/or create a new one if you run into any trouble.

**Comment by markus99** [comment]
Amazing, ty!  Super slammed with work and family for a bit, so might be a delay reporting back, but will do asap.  Nice work and ty again!
